# Tutorial 5: Association Rules Mining

## Dataset definition and preprocessing

### As the apriori algorithm does not accept numerical values, the income is discretized

In [103]:
# bank dataset preprocessing
import pandas as pd
df = pd.read_csv("./bank-data.csv")
del df["id"]
df["income"] = pd.cut(df["income"],10)
dataset = []
for index, row in df.iterrows():
    row = [col+"="+str(row[col]) for col in list(df)]
    dataset.append(row)

### Apriori algorithm find the frequent items in a dataset so that they are used in association rules

In [104]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
frequent_itemsets = apriori(df, min_support=0.3, use_colnames=True)

frequent_itemsets

#frequentItemsets, supports = apriori(dataset, 0.3)

#for f in frequentItemsets:
#    print("{} - {}".format(f,supports[f]))

     support                                      itemsets
0   0.506667                                      (car=NO)
1   0.493333                                     (car=YES)
2   0.438333                                  (children=0)
3   0.758333                             (current_act=YES)
4   0.340000                                  (married=NO)
5   0.660000                                 (married=YES)
6   0.651667                                 (mortgage=NO)
7   0.348333                                (mortgage=YES)
8   0.543333                                      (pep=NO)
9   0.456667                                     (pep=YES)
10  0.448333                           (region=INNER_CITY)
11  0.310000                                 (save_act=NO)
12  0.690000                                (save_act=YES)
13  0.500000                                  (sex=FEMALE)
14  0.500000                                    (sex=MALE)
15  0.391667                     (car=NO, current_act=YES)
16  0.336667                         (car=NO, married=YES)
17  0.328333                         (car=NO, mortgage=NO)
18  0.341667                        (car=NO, save_act=YES)
19  0.366667                    (car=YES, current_act=YES)
20  0.323333                        (car=YES, married=YES)
21  0.323333                        (car=YES, mortgage=NO)
22  0.348333                       (car=YES, save_act=YES)
23  0.331667                 (current_act=YES, children=0)
24  0.300000                     (married=YES, children=0)
25  0.488333                (current_act=YES, married=YES)
26  0.501667                (current_act=YES, mortgage=NO)
27  0.406667                     (current_act=YES, pep=NO)
28  0.351667                    (current_act=YES, pep=YES)
29  0.341667          (region=INNER_CITY, current_act=YES)
30  0.531667               (current_act=YES, save_act=YES)
31  0.383333                 (sex=FEMALE, current_act=YES)
32  0.375000                   (current_act=YES, sex=MALE)
33  0.435000                    (married=YES, mortgage=NO)
34  0.403333                         (married=YES, pep=NO)
35  0.461667                   (save_act=YES, married=YES)
36  0.325000                     (sex=FEMALE, married=YES)
37  0.335000                       (sex=MALE, married=YES)
38  0.348333                         (mortgage=NO, pep=NO)
39  0.303333                        (pep=YES, mortgage=NO)
40  0.450000                   (save_act=YES, mortgage=NO)
41  0.341667                     (sex=FEMALE, mortgage=NO)
42  0.310000                       (sex=MALE, mortgage=NO)
43  0.391667                        (save_act=YES, pep=NO)
44  0.343333                    (sex=FEMALE, save_act=YES)
45  0.346667                      (sex=MALE, save_act=YES)
46  0.331667   (current_act=YES, married=YES, mortgage=NO)
47  0.343333  (current_act=YES, save_act=YES, married=YES)
48  0.353333  (current_act=YES, save_act=YES, mortgage=NO)
49  0.306667      (save_act=YES, married=YES, mortgage=NO)

### Finally, the association rules are generated from this list

#### Sorted by confidence > 0,7

In [110]:
from mlxtend.frequent_patterns import association_rules

rules_confidence = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)
rules_confidence

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(car=NO),(current_act=YES),0.506667,0.758333,0.391667,0.773026,1.019375,0.007444,1.064734
1,(car=YES),(current_act=YES),0.493333,0.758333,0.366667,0.743243,0.980101,-0.007444,0.941228
2,(car=YES),(save_act=YES),0.493333,0.690000,0.348333,0.706081,1.023306,0.007933,1.054713
3,(children=0),(current_act=YES),0.438333,0.758333,0.331667,0.756654,0.997785,-0.000736,0.993099
4,(married=YES),(current_act=YES),0.660000,0.758333,0.488333,0.739899,0.975691,-0.012167,0.929126
5,(mortgage=NO),(current_act=YES),0.651667,0.758333,0.501667,0.769821,1.015149,0.007486,1.049907
6,(pep=NO),(current_act=YES),0.543333,0.758333,0.406667,0.748466,0.986988,-0.005361,0.960772
7,(pep=YES),(current_act=YES),0.456667,0.758333,0.351667,0.770073,1.015481,0.005361,1.051058
8,(region=INNER_CITY),(current_act=YES),0.448333,0.758333,0.341667,0.762082,1.004943,0.001681,1.015755
9,(current_act=YES),(save_act=YES),0.758333,0.690000,0.531667,0.701099,1.016085,0.008417,1.037132
10,(save_act=YES),(current_act=YES),0.690000,0.758333,0.531667,0.770531,1.016085,0.008417,1.053158
11,(sex=FEMALE),(current_act=YES),0.500000,0.758333,0.383333,0.766667,1.010989,0.004167,1.035714
12,(sex=MALE),(current_act=YES),0.500000,0.758333,0.375000,0.750000,0.989011,-0.004167,0.966667
13,(pep=NO),(married=YES),0.543333,0.660000,0.403333,0.742331,1.124744,0.044733,1.319524
14,(pep=NO),(save_act=YES),0.543333,0.690000,0.391667,0.720859,1.044723,0.016767,1.110549
15,"(married=YES, mortgage=NO)",(current_act=YES),0.435000,0.758333,0.331667,0.762452,1.005431,0.001792,1.017339
16,"(current_act=YES, married=YES)",(save_act=YES),0.488333,0.690000,0.343333,0.703072,1.018944,0.006383,1.044023
17,"(save_act=YES, married=YES)",(current_act=YES),0.461667,0.758333,0.343333,0.743682,0.980680,-0.006764,0.942840
18,"(current_act=YES, mortgage=NO)",(save_act=YES),0.501667,0.690000,0.353333,0.704319,1.020752,0.007183,1.048427
19,"(save_act=YES, mortgage=NO)",(current_act=YES),0.450000,0.758333,0.353333,0.785185,1.035409,0.012083,1.125000
20,"(married=YES, mortgage=NO)",(save_act=YES),0.435000,0.690000,0.306667,0.704981,1.021711,0.006517,1.050779

#### Sorted by support > 0,4

In [120]:
rules_support = association_rules(frequent_itemsets, metric="support", min_threshold=0.4)
rules_support

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(current_act=YES),(married=YES),0.758333,0.660000,0.488333,0.643956,0.975691,-0.012167,0.954938
1,(married=YES),(current_act=YES),0.660000,0.758333,0.488333,0.739899,0.975691,-0.012167,0.929126
2,(current_act=YES),(mortgage=NO),0.758333,0.651667,0.501667,0.661538,1.015149,0.007486,1.029167
3,(mortgage=NO),(current_act=YES),0.651667,0.758333,0.501667,0.769821,1.015149,0.007486,1.049907
4,(current_act=YES),(pep=NO),0.758333,0.543333,0.406667,0.536264,0.986988,-0.005361,0.984755
5,(pep=NO),(current_act=YES),0.543333,0.758333,0.406667,0.748466,0.986988,-0.005361,0.960772
6,(current_act=YES),(save_act=YES),0.758333,0.690000,0.531667,0.701099,1.016085,0.008417,1.037132
7,(save_act=YES),(current_act=YES),0.690000,0.758333,0.531667,0.770531,1.016085,0.008417,1.053158
8,(married=YES),(mortgage=NO),0.660000,0.651667,0.435000,0.659091,1.011393,0.004900,1.021778
9,(mortgage=NO),(married=YES),0.651667,0.660000,0.435000,0.667519,1.011393,0.004900,1.022615
10,(married=YES),(pep=NO),0.660000,0.543333,0.403333,0.611111,1.124744,0.044733,1.174286
11,(pep=NO),(married=YES),0.543333,0.660000,0.403333,0.742331,1.124744,0.044733,1.319524
12,(save_act=YES),(married=YES),0.690000,0.660000,0.461667,0.669082,1.013761,0.006267,1.027445
13,(married=YES),(save_act=YES),0.660000,0.690000,0.461667,0.699495,1.013761,0.006267,1.031597
14,(save_act=YES),(mortgage=NO),0.690000,0.651667,0.450000,0.652174,1.000778,0.000350,1.001458
15,(mortgage=NO),(save_act=YES),0.651667,0.690000,0.450000,0.690537,1.000778,0.000350,1.001736

#### Sorted by lift > 1

In [125]:
rules_lift = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules_lift

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(car=NO),(current_act=YES),0.506667,0.758333,0.391667,0.773026,1.019375,0.007444,1.064734
1,(current_act=YES),(car=NO),0.758333,0.506667,0.391667,0.516484,1.019375,0.007444,1.020303
2,(car=NO),(married=YES),0.506667,0.660000,0.336667,0.664474,1.006778,0.002267,1.013333
3,(married=YES),(car=NO),0.660000,0.506667,0.336667,0.510101,1.006778,0.002267,1.007010
4,(car=YES),(mortgage=NO),0.493333,0.651667,0.323333,0.655405,1.005737,0.001844,1.010850
5,(mortgage=NO),(car=YES),0.651667,0.493333,0.323333,0.496164,1.005737,0.001844,1.005618
6,(car=YES),(save_act=YES),0.493333,0.690000,0.348333,0.706081,1.023306,0.007933,1.054713
7,(save_act=YES),(car=YES),0.690000,0.493333,0.348333,0.504831,1.023306,0.007933,1.023220
8,(married=YES),(children=0),0.660000,0.438333,0.300000,0.454545,1.036986,0.010700,1.029722
9,(children=0),(married=YES),0.438333,0.660000,0.300000,0.684411,1.036986,0.010700,1.077349
10,(current_act=YES),(mortgage=NO),0.758333,0.651667,0.501667,0.661538,1.015149,0.007486,1.029167
11,(mortgage=NO),(current_act=YES),0.651667,0.758333,0.501667,0.769821,1.015149,0.007486,1.049907
12,(current_act=YES),(pep=YES),0.758333,0.456667,0.351667,0.463736,1.015481,0.005361,1.013183
13,(pep=YES),(current_act=YES),0.456667,0.758333,0.351667,0.770073,1.015481,0.005361,1.051058
14,(region=INNER_CITY),(current_act=YES),0.448333,0.758333,0.341667,0.762082,1.004943,0.001681,1.015755
15,(current_act=YES),(region=INNER_CITY),0.758333,0.448333,0.341667,0.450549,1.004943,0.001681,1.004033
16,(current_act=YES),(save_act=YES),0.758333,0.690000,0.531667,0.701099,1.016085,0.008417,1.037132
17,(save_act=YES),(current_act=YES),0.690000,0.758333,0.531667,0.770531,1.016085,0.008417,1.053158
18,(sex=FEMALE),(current_act=YES),0.500000,0.758333,0.383333,0.766667,1.010989,0.004167,1.035714
19,(current_act=YES),(sex=FEMALE),0.758333,0.500000,0.383333,0.505495,1.010989,0.004167,1.011111
20,(married=YES),(mortgage=NO),0.660000,0.651667,0.435000,0.659091,1.011393,0.004900,1.021778
21,(mortgage=NO),(married=YES),0.651667,0.660000,0.435000,0.667519,1.011393,0.004900,1.022615
22,(married=YES),(pep=NO),0.660000,0.543333,0.403333,0.611111,1.124744,0.044733,1.174286
23,(pep=NO),(married=YES),0.543333,0.660000,0.403333,0.742331,1.124744,0.044733,1.319524
24,(save_act=YES),(married=YES),0.690000,0.660000,0.461667,0.669082,1.013761,0.006267,1.027445
25,(married=YES),(save_act=YES),0.660000,0.690000,0.461667,0.699495,1.013761,0.006267,1.031597
26,(sex=MALE),(married=YES),0.500000,0.660000,0.335000,0.670000,1.015152,0.005000,1.030303
27,(married=YES),(sex=MALE),0.660000,0.500000,0.335000,0.507576,1.015152,0.005000,1.015385
28,(pep=YES),(mortgage=NO),0.456667,0.651667,0.303333,0.664234,1.019284,0.005739,1.037428
29,(mortgage=NO),(pep=YES),0.651667,0.456667,0.303333,0.465473,1.019284,0.005739,1.016475
30,(save_act=YES),(mortgage=NO),0.690000,0.651667,0.450000,0.652174,1.000778,0.000350,1.001458
31,(mortgage=NO),(save_act=YES),0.651667,0.690000,0.450000,0.690537,1.000778,0.000350,1.001736
32,(sex=FEMALE),(mortgage=NO),0.500000,0.651667,0.341667,0.683333,1.048593,0.015833,1.100000
33,(mortgage=NO),(sex=FEMALE),0.651667,0.500000,0.341667,0.524297,1.048593,0.015833,1.051075
34,(save_act=YES),(pep=NO),0.690000,0.543333,0.391667,0.567633,1.044723,0.016767,1.056201
35,(pep=NO),(save_act=YES),0.543333,0.690000,0.391667,0.720859,1.044723,0.016767,1.110549
36,(sex=MALE),(save_act=YES),0.500000,0.690000,0.346667,0.693333,1.004831,0.001667,1.010870
37,(save_act=YES),(sex=MALE),0.690000,0.500000,0.346667,0.502415,1.004831,0.001667,1.004854
38,"(current_act=YES, married=YES)",(mortgage=NO),0.488333,0.651667,0.331667,0.679181,1.042221,0.013436,1.085762
39,"(current_act=YES, mortgage=NO)",(married=YES),0.501667,0.660000,0.331667,0.661130,1.001711,0.000567,1.003333
40,"(married=YES, mortgage=NO)",(current_act=YES),0.435000,0.758333,0.331667,0.762452,1.005431,0.001792,1.017339
41,(current_act=YES),"(married=YES, mortgage=NO)",0.758333,0.435000,0.331667,0.437363,1.005431,0.001792,1.004199
42,(married=YES),"(current_act=YES, mortgage=NO)",0.660000,0.501667,0.331667,0.502525,1.001711,0.000567,1.001726
43,(mortgage=NO),"(current_act=YES, married=YES)",0.651667,0.488333,0.331667,0.508951,1.042221,0.013436,1.041988
44,"(current_act=YES, married=YES)",(save_act=YES),0.488333,0.690000,0.343333,0.703072,1.018944,0.006383,1.044023
45,(save_act=YES),"(current_act=YES, married=YES)",0.690000,0.488333,0.343333,0.497585,1.018944,0.006383,1.018413
46,"(current_act=YES, save_act=YES)",(mortgage=NO),0.531667,0.651667,0.353333,0.664577,1.019811,0.006864,1.038489
47,"(current_act=YES, mortgage=NO)",(save_act=YES),0.501667,0.690000,0.353333,0.704319,1.020752,0.007183,1.048427
48,"(save_act=YES, mortgage=NO)",(current_act=YES),0.450000,0.758333,0.353333,0.785185,1.035409,0.012083,1.125000
49,(current_act=YES),"(save_act=YES, mortgage=NO)",0.758333,0.450000,0.353333,0.465934,1.035409,0.012083,1.029835
50,(save_act=YES),"(current_act=YES, mortgage=NO)",0.690000,0.501667,0.353333,0.512077,1.020752,0.007183,1.021337
51,(mortgage=NO),"(current_act=YES, save_act=YES)",0.651667,0.531667,0.353333,0.542199,1.019811,0.006864,1.023007
52,"(save_act=YES, married=YES)",(mortgage=NO),0.461667,0.651667,0.306667,0.664260,1.019325,0.005814,1.037509
53,"(save_act=YES, mortgage=NO)",(married=YES),0.450000,0.660000,0.306667,0.681481,1.032548,0.009667,1.067442
54,"(married=YES, mortgage=NO)",(save_act=YES),0.435000,0.690000,0.306667,0.704981,1.021711,0.006517,1.050779
55,(save_act=YES),"(married=YES, mortgage=NO)",0.690000,0.435000,0.306667,0.444444,1.021711,0.006517,1.017000
56,(married=YES),"(save_act=YES, mortgage=NO)",0.660000,0.450000,0.306667,0.464646,1.032548,0.009667,1.027358
57,(mortgage=NO),"(save_act=YES, married=YES)",0.651667,0.461667,0.306667,0.470588,1.019325,0.005814,1.016852